# Project Information
site_name: Comprehensive Technology Documentation
site_description: A unified guide covering FastAPI, Application Architecture, DevOps, DevSecOps, CI/CD, and related software engineering practices.
site_author: KDasaradha525
site_url: https://night-fury.onrender.com/ # Use the actual deployment URL when available

# Repository Information
repo_name: KDasaradha/my-tutorials
repo_url: https://github.com/KDasaradha/my-tutorials # Ensure this matches the correct repo
edit_uri: blob/main/content/docs/ # Ensure this points to the markdown files location

# Copyright Information
copyright: "© 2025 KDasaradha525. All rights reserved."

# Assets - paths relative to public directory
# Assumes files are in public/assets/
logo_path: /assets/toothless_logo.jpg # Updated path
favicon_path: /assets/toothless_icon.ico # Updated path

# Navigation Structure
nav:
  - title: Home
    path: index
  - title: About
    path: about
  - title: Comprehensive Guide
    path: guides/comprehensive-fastapi-guide # Parent links to the top overview page
    children:
      # Section 1
      - title: 1. Intro to APIs & FastAPI
        path: guides/comprehensive-fastapi-guide#1-introduction-to-apis-and-fastapi
      - title: 1.1 What is an API?
        path: api-fundamentals/what-is-an-api
      - title: 1.2 Types of APIs
        path: api-fundamentals/types-of-apis
      - title: 1.3 REST API Principles
        path: api-fundamentals/rest-api-principles
      - title: 1.4 Introduction to FastAPI
        path: fastapi/introduction/introduction-to-fastapi
      # Section 2
      - title: 2. Core FastAPI Concepts
        path: guides/comprehensive-fastapi-guide#2-core-fastapi-concepts
      - title: 2.1 Basic FastAPI Application
        path: fastapi/core-concepts/basic-application
      - title: 2.2 Path and Query Parameters
        path: fastapi/core-concepts/path-and-query-parameters
      - title: 2.3 Request Body and Pydantic Models
        path: fastapi/core-concepts/request-body-and-pydantic-models
      - title: 2.4 Response Models and Status Codes
        path: fastapi/core-concepts/response-models-and-status-codes
      - title: 2.5 Async Endpoints
        path: fastapi/core-concepts/async-endpoints
      # Section 3
      - title: 3. Database Handling with SQLAlchemy
        path: guides/comprehensive-fastapi-guide#3-database-handling-with-sqlalchemy
      - title: 3.1 Introduction to SQLAlchemy
        path: sqlalchemy/introduction/introduction-to-sqlalchemy
      - title: 3.2 FastAPI with SQLAlchemy
        path: sqlalchemy/fastapi-integration/session-management
      - title: 3.3 Pydantic and SQLAlchemy Integration
        path: sqlalchemy/pydantic-integration/pydantic-sqlalchemy-integration
      - title: 3.4 SQLAlchemy Best Practices
        path: sqlalchemy/best-practices/general-best-practices
      - title: 3.5 Table Creation Methods
        path: sqlalchemy/modeling/table-creation-methods
      - title: 3.6 Utilizing Declarative Base Effectively
        path: sqlalchemy/modeling/declarative-base-usage
      - title: 3.7 Multi-Tenant Architectures
        path: sqlalchemy/advanced-patterns/multi-tenancy
      # Section 4
      - title: 4. Advanced FastAPI Features
        path: guides/comprehensive-fastapi-guide#4-advanced-fastapi-features
      - title: 4.1 Dependency Injection
        path: fastapi/advanced-features/dependency-injection
      - title: 4.2 Background Tasks
        path: fastapi/advanced-features/background-tasks
      - title: 4.3 WebSockets
        path: fastapi/advanced-features/websockets
      - title: 4.4 FastAPI Admin
        path: fastapi/ecosystem/fastapi-admin
      - title: 4.5 Custom Middleware
        path: fastapi/advanced-features/custom-middleware
      - title: 4.6 Event Handlers (Startup/Shutdown)
        path: fastapi/advanced-features/event-handlers
      - title: 4.7 Custom APIRouter
        path: fastapi/routing/custom-apirouter
      - title: 4.8 Dependency Overrides
        path: fastapi/testing/dependency-overrides
      - title: 4.9 Custom Exception Handlers
        path: fastapi/error-handling/custom-exception-handlers
      - title: 4.10 Streaming Responses
        path: fastapi/responses/streaming-responses
      - title: 4.11 File Uploads
        path: fastapi/requests/file-uploads
      - title: 4.12 OpenAPI Customization
        path: fastapi/openapi/customization
      - title: 4.13 Server-Sent Events (SSE)
        path: fastapi/real-time/server-sent-events
      - title: 4.14 Custom Response Classes
        path: fastapi/responses/custom-response-classes
      - title: 4.15 Request Context
        path: fastapi/advanced-features/request-context
      # Section 5
      - title: 5. FastAPI Security
        path: guides/comprehensive-fastapi-guide#5-fastapi-security
      - title: 5.1 Security Mechanisms Overview
        path: fastapi/security/overview
      - title: 5.2 Basic Authentication
        path: fastapi/security/basic-authentication
      - title: 5.3 JWT Authentication
        path: fastapi/security/jwt-authentication
      - title: 5.4 OAuth2 Authentication
        path: fastapi/security/oauth2-authentication
      - title: 5.5 API Key Authentication
        path: fastapi/security/api-key-authentication
      - title: 5.6 Rate Limiting
        path: fastapi/security/rate-limiting
      - title: 5.7 CSRF Protection
        path: fastapi/security/csrf-protection
      - title: 5.8 Advanced Security Techniques
        path: fastapi/security/advanced-techniques
      - title: 5.9 Token Refresh Mechanisms
        path: fastapi/security/token-refresh
      - title: 5.10 Secure Cookie-Based Authentication
        path: fastapi/security/cookie-authentication
      - title: 5.11 Zero Trust Security Model
        path: fastapi/security/zero-trust
      # Section 6
      - title: 6. Performance & Optimization
        path: guides/comprehensive-fastapi-guide#6-performance-and-optimization
      - title: 6.1 Optimizing FastAPI Performance
        path: fastapi/performance/optimizing-fastapi-performance
      - title: 6.2 Error Handling and Logging
        path: fastapi/performance/error-handling-and-logging
      - title: 6.3 SQLAlchemy Performance Optimization
        path: sqlalchemy/performance/sqlalchemy-performance
      # Section 7
      - title: 7. Advanced SQLAlchemy
        path: guides/comprehensive-fastapi-guide#7-advanced-sqlalchemy-techniques
      - title: 7.1 Advanced Querying
        path: sqlalchemy/advanced-techniques/advanced-querying
      - title: 7.2 Triggers and Views
        path: sqlalchemy/advanced-techniques/triggers-and-views
      - title: 7.3 Hybrid Properties and Methods
        path: sqlalchemy/advanced-techniques/hybrid-properties
      - title: 7.4 Inheritance Mapping
        path: sqlalchemy/advanced-techniques/inheritance-mapping
      - title: 7.5 ORM Events
        path: sqlalchemy/advanced-techniques/orm-events
      - title: 7.6 Async SQLAlchemy
        path: sqlalchemy/async/async-sqlalchemy
      # Section 8
      - title: 8. Pydantic Advanced Features
        path: guides/comprehensive-fastapi-guide#8-pydantic-advanced-features
      - title: 8.1 Custom Validators
        path: pydantic/advanced-features/custom-validators
      - title: 8.2 Settings Management
        path: pydantic/advanced-features/settings-management
      - title: 8.3 Complex Nested Models
        path: pydantic/advanced-features/complex-nested-models
      - title: 8.4 Serialization Customization
        path: pydantic/advanced-features/serialization
      - title: 8.5 Generic Models
        path: pydantic/advanced-features/generic-models
      - title: 8.6 Dataclasses Integration
        path: pydantic/advanced-features/dataclasses
      # Section 9
      - title: 9. Async Programming
        path: guides/comprehensive-fastapi-guide#9-async-programming
      - title: 9.1 Sync vs. Async
        path: async-programming/sync-vs-async
      - title: 9.2 Async DB Connections
        path: async-programming/async-db-connections
      - title: 9.3 Async Middleware
        path: async-programming/async-middleware
      - title: 9.4 Running Tasks Concurrently
        path: fastapi/performance/optimizing-fastapi-performance # Reuses existing relevant section
      - title: 9.5 Async Generators
        path: data-streaming/async-generators # Reuses existing relevant section
      # Section 10
      - title: 10. Integrations & Architectures
        path: guides/comprehensive-fastapi-guide#10-integrations-and-architectures
      - title: 10.1 Third-Party Integrations
        path: integrations-and-architectures/third-party-integrations
      - title: 10.2 GraphQL Integration
        path: integrations-and-architectures/graphql-integration
      - title: 10.3 Microservices Architecture
        path: integrations-and-architectures/microservices-architecture
      - title: 10.4 Celery Integration
        path: integrations-and-architectures/celery-integration
      - title: 10.5 Kafka Integration
        path: integrations-and-architectures/kafka-integration
      # Section 11
      - title: 11. Deployment & Testing
        path: guides/comprehensive-fastapi-guide#11-deployment-and-testing
      - title: 11.1 Deploying FastAPI
        path: deployment-and-testing/deploying-fastapi
      - title: 11.2 Testing FastAPI
        path: deployment-and-testing/testing-fastapi
      - title: 11.3 Monitoring and Logging
        path: deployment-and-testing/monitoring-and-logging
      - title: 11.4 Load Testing
        path: deployment-and-testing/load-testing
      # Section 12
      - title: 12. FastAPI Pro-Level Features
        path: guides/comprehensive-fastapi-guide#12-fastapi-pro-level-features
      - title: 12.1 Custom ASGI Middleware
        path: fastapi-pro/custom-asgi-middleware
      - title: 12.2 HTTP/2 & gRPC
        path: fastapi-pro/http2-grpc
      - title: 12.3 Dynamic Route Generation
        path: fastapi-pro/dynamic-route-generation
      # Section 13
      - title: 13. API Versioning
        path: guides/comprehensive-fastapi-guide#13-api-versioning
      - title: 13.1 Versioning Strategies
        path: api-versioning/strategies
      # Section 14
      - title: 14. AI/ML Integration
        path: guides/comprehensive-fastapi-guide#14-ai-and-machine-learning-integration
      - title: 14.1 Serving ML Models
        path: ai-ml-integration/serving-ml-models
      # Section 15
      - title: 15. Serverless Optimizations
        path: guides/comprehensive-fastapi-guide#15-serverless-optimizations
      - title: 15.1 Optimizing for Serverless
        path: serverless-optimizations/optimizing-for-serverless
      # Section 16
      - title: 16. Advanced Documentation
        path: guides/comprehensive-fastapi-guide#16-advanced-documentation-practices
      - title: 16.1 Enhanced API Documentation
        path: advanced-documentation/enhanced-api-docs
      # Section 17
      - title: 17. Data Streaming
        path: guides/comprehensive-fastapi-guide#17-data-streaming-with-async-generators
      - title: 17.1 Async Data Streaming
        path: data-streaming/async-generators
      # Section 18
      - title: 18. FastAPI with Rust
        path: guides/comprehensive-fastapi-guide#18-fastapi-with-rust-extensions
      - title: 18.1 Integrating Rust
        path: fastapi-with-rust/integrating-rust
      # Section 19
      - title: 19. SQLAlchemy w/ Data Lakes
        path: guides/comprehensive-fastapi-guide#19-sqlalchemy-with-data-lakes
      - title: 19.1 Querying Data Lakes
        path: sqlalchemy-with-datalakes/querying-data-lakes
      # Section 20
      - title: 20. Pydantic w/ Schema Registry
        path: guides/comprehensive-fastapi-guide#20-pydantic-with-schema-registry
      - title: 20.1 Schema Registry Integration
        path: pydantic-with-schema-registry/integration
      # Section 21
      - title: 21. Async GraphQL Subs
        path: guides/comprehensive-fastapi-guide#21-async-graphql-subscriptions
      - title: 21.1 Implementing GraphQL Subscriptions
        path: async-graphql-subscriptions/implementation
      # Section 22
      - title: 22. FastAPI Edge Computing
        path: guides/comprehensive-fastapi-guide#22-fastapi-with-edge-computing
      - title: 22.1 Deploying FastAPI on Edge Nodes
        path: fastapi-edge-computing/deployment
      # Section 23
      - title: 23. Zero-Downtime Migrations
        path: guides/comprehensive-fastapi-guide#23-zero-downtime-db-migrations
      - title: 23.1 Zero-Downtime DB Migrations
        path: sqlalchemy/migrations/zero-downtime
      # Section 24
      - title: 24. FastAPI w/ Diff. Privacy
        path: guides/comprehensive-fastapi-guide#24-fastapi-with-differential-privacy
      - title: 24.1 Implementing Differential Privacy
        path: fastapi/privacy/differential-privacy
      # Section 25
      - title: 25. Pydantic Static Typing
        path: guides/comprehensive-fastapi-guide#25-pydantic-with-static-type-checking
      - title: 25.1 Static Type Checking for Pydantic
        path: pydantic/type-checking/static-analysis
  - title: Guides
    children:
      - title: Getting Started
        path: guides/getting-started
      - title: Advanced Topics
        path: guides/advanced-topics
  - title: Python
    children:
      - title: Basic
        path: python/basic
      - title: Intermediate
        path: python/intermediate
      - title: Advanced
        path: python/advanced
      - title: Pro
        path: python/pro
      - title: Hidden Gems
        path: python/hidden-gems
  - title: FastAPI
    children:
      - title: Introduction
        path: fastapi/introduction # Index for the section
      - title: Core Concepts
        path: fastapi/core-concepts # Index for the section
      - title: Advanced Features
        path: fastapi/advanced-features # Index for the section
      - title: Pro-Level Features
        path: fastapi-pro # Index for the section
      - title: Performance & Optimization
        path: fastapi/performance # Index for the section
      - title: Security
        path: fastapi/security # Index for the section
      - title: Hidden Gems
        path: fastapi/hidden-gems
  - title: SQLAlchemy
    children:
      - title: Introduction
        path: sqlalchemy/introduction # Index for the section
      - title: FastAPI Integration
        path: sqlalchemy/fastapi-integration # Index for the section
      - title: Pydantic Integration
        path: sqlalchemy/pydantic-integration # Index for the section
      - title: Modeling
        path: sqlalchemy/modeling # Index for the section
      - title: Advanced Techniques
        path: sqlalchemy/advanced-techniques # Index for the section
      - title: Performance & Optimization
        path: sqlalchemy/performance/sqlalchemy-performance
      - title: Advanced Patterns
        path: sqlalchemy/advanced-patterns # Index for the section
      - title: Async
        path: sqlalchemy/async # Index for the section
      - title: Migrations
        path: sqlalchemy/migrations # Index for the section
      - title: Best Practices
        path: sqlalchemy/best-practices # Index for the section
      - title: Hidden Gems
        path: sqlalchemy/hidden-gems
  - title: Pydantic
    children:
      - title: Basic
        path: pydantic/basic
      - title: Intermediate
        path: pydantic/intermediate
      - title: Advanced Features
        path: pydantic/advanced-features # Index for the section
      - title: Pro
        path: pydantic/pro
      - title: Type Checking
        path: pydantic/type-checking # Index for the section
      - title: Hidden Gems
        path: pydantic/hidden-gems
  - title: PostgreSQL
    children:
      - title: Basic
        path: postgresql/basic
      - title: Intermediate
        path: postgresql/intermediate
      - title: Advanced
        path: postgresql/advanced
      - title: Pro
        path: postgresql/pro
      - title: Hidden Gems
        path: postgresql/hidden-gems
  - title: MongoDB
    children:
      - title: Basic
        path: mongodb/basic
      - title: Intermediate
        path: mongodb/intermediate
      - title: Advanced
        path: mongodb/advanced
      - title: Pro
        path: mongodb/pro
      - title: Hidden Gems
        path: mongodb/hidden-gems
  - title: JavaScript
    children:
      - title: Basic
        path: javascript/basic
      - title: Intermediate
        path: javascript/intermediate
      - title: Advanced
        path: javascript/advanced
      - title: Pro
        path: javascript/pro
      - title: Hidden Gems
        path: javascript/hidden-gems
  - title: React
    children:
      - title: Basic
        path: react/basic
      - title: Intermediate
        path: react/intermediate
      - title: Advanced
        path: react/advanced
      - title: Pro
        path: react/pro
      - title: Hidden Gems
        path: react/hidden-gems
  - title: Next.js
    children:
      - title: Basic
        path: nextjs/basic
      - title: Intermediate
        path: nextjs/intermediate
      - title: Advanced
        path: nextjs/advanced
      - title: Pro
        path: nextjs/pro
      - title: Hidden Gems
        path: nextjs/hidden-gems
  - title: HTML
    children:
      - title: Basic
        path: html/basic
      - title: Intermediate
        path: html/intermediate
      - title: Advanced
        path: html/advanced
      - title: Pro
        path: html/pro
      - title: Hidden Gems
        path: html/hidden-gems
  - title: CSS
    children:
      - title: Basic
        path: css/basic
      - title: Intermediate
        path: css/intermediate
      - title: Advanced
        path: css/advanced
      - title: Pro
        path: css/pro
      - title: Hidden Gems
        path: css/hidden-gems

# Theme Configuration
theme:
  default: system # can be light, dark, or system
  options:
    - light
    - dark

# Search Configuration
search:
  enabled: true
